### ISSUE TITLE
defining default Urls for social links possible?

### ISSUE THREAD

**Issue by InfGame** [voidlabs/versafix-template#40]
Hey! I am trying to edit the vesafix template to fit our needs. which includes defining default href URLs for the social Icons.

I wanted to ask if this is even possible because I have tried it in a few different ways including:

Defining the URL in the block definition:
```css
socialBlock {
        label: Social Block;
        properties: -//- fbUrl=someUrl -//-
        variant: socialIconType;
        theme: frameTheme
      }
```
which yields me this error:
` Exception while parsing the template Exception parsing expression @[fbUrl] [] Trying to set a new default value for socialBlock fbUrl while it already exists (current: test, new: ) `

or defining it through the actual Url attribute:
```css
fbUrl {
        label: Facebook Link;
        extend: url;
        default: someURL
      }
```
which does not throw an error but does not seem to set a default value.
